title: UKHealthCamp
name: UKHealthCamp
baseurl: ""
url: "https://ukhealthcamp.com"
repository: ukhealthcamp/ukhealthcamp.github.io
markdown: kramdown
highlighter: null
sass:
  style: compressed
  
show_alert: false

plugins:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:categories/:title

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]
